const menuArray = [
  {
    name: "Patria Arg gloves",
    category: "gloves",
    tags: ["pepperoni", "mushrom", "mozarella"],
    id: 0,
    price: 77.5,
    image: "./products/arg1.webp",
  },
  {
    name: "Triple campeon gloves",
    category: "gloves",
    tags: ["beef", "cheese", "lettuce"],
    price: 77.5,
    image: "./products/arg2.webp",
    id: 1,
  },
  {
    name: "Pixel gloves",
    category: "gloves",
    tags: ["grain, hops, yeast, water"],
    price: 42.3,
    image: "./products/pixel.webp",
    id: 2,
  },
  {
    name: "Blue shin guard",
    category: "shin guard",
    tags: ["grain, hops, yeast, water"],
    price: 22.8,
    image: "./products/shinGuard.webp",
    id: 3,
  },
  {
    name: "Sock shin guard",
    category: "shin guard",
    tags: ["grain, hops, yeast, water"],
    price: 22.8,
    image: "./products/socks.webp",
    id: 3,
  },
  {
    name: "Boxing head gear face saver",
    category: "headgear",
    tags: ["grain, hops, yeast, water"],
    price: 98,
    image: "./products/cabezal.webp",
    id: 4,
  },
  {
    name: "Boxing Full head gear",
    category: "headgear",
    tags: ["grain, hops, yeast, water"],
    price: 98,
    image: "./products/cabezalFull.webp",
    id: 5,
  },
];
